### ISSUE TITLE
After Upgrading to version 2.0 stops working - Blue led blinking

### ISSUE THREAD

**Issue by tuliosilvajunior** [mwood77/winderoo#57]
After the upgrade process is successful, the connection to the wireless working is flapping, and the blue led is blinking variating the speed. It returns 1 ping and then a lot of timeouts. 
If I erase the flash and downgrade to the version 1.0 everything works fine. Any Idea how to debug?
<img width="731" alt="image" src="https://github.com/mwood77/winderoo/assets/13374329/9d7bd927-121c-4cfd-9c2c-e5bf17dd95d3">

**Comment by mwood77** [comment]
That's a new one.

When you're seeing these timeouts, the onboard LED is blinking? Can you connect it to your computer and see what is happening in the Serial Monitor?
