### ISSUE TITLE
404 - Resource Not Found

### ISSUE THREAD

**Issue by whatthefilament** [mwood77/winderoo#65]
I just went through setup, everything seemed to go fine. When i finished connecting to wifi it rebooted and appeared normal. Tried Navigating to Winderoo.local and got an error message 404 - Resource Not found. 

I tried erasing the flash memory
![IMG_0107](https://github.com/user-attachments/assets/ed4f4fd1-ab0a-4d07-a82d-dae8cc8fcadc)
![IMG_0108](https://github.com/user-attachments/assets/93f6210e-6df7-4e64-9aa5-03a140e57c8d)
, rebuilding the firmware and reinstalling but got the same thing.

**Comment by mwood77** [comment]
Hi!

This is a symptom of the file system image missing. There are two upload steps when you flash the microcontroller. If you look the image on step 5 here:

https://github.com/mwood77/winderoo/blob/main/docs/install-software.md#flashing-your-microcontroller

And then perform step 7, you should be all fixed!

**Comment by whatthefilament** [comment]
hahaha, my god, how did I miss that step 7 was a different upload. Thank you. That fixed it immediately and I am up and running!
