### ISSUE TITLE
Wifi captive page issue

### ISSUE THREAD

**Issue by SpookleZz** [mwood77/winderoo#70]
Hi, Love this project so far, however, I dont get any captive pages appear when connecting to the winderoo setup wifi net work. Using android version 14.

**Comment by SpookleZz** [comment]
Quick update, captive portal launches on an Iphone I've dug out, so must be an android 14 issue

**Comment by mwood77** [comment]
Hmm, this is an issue I've seen with android devices before. It's a long running issue with Android's (lack of) mDNS support (resolving `.local` domains on your network).

There's a very large issue tracker here talking about it: https://issuetracker.google.com/issues/140786115

It's marked as fixed, but I think that only applies to Android 14. From there, it's dependent on your devices OEM pushing that update. Who made the phone that worked, and the phone that didn't?
